### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by mikebranstein** [EddyVerbruggen/nativescript-nodeify#5]
I'm using v0.5.0 and am running into an issue on a clean project:
```
tns create nodeify-test
tns platform add android; tns platform add ios
tns plugin add nativescript-nodeify
tns build android
```

mikeb-macbook-pro:nodeify-test mike$ tns build android
Executing before-prepare hook from /Users/mike/Documents/temp/nodeify-test/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook from /Users/mike/Documents/temp/nodeify-test/hooks/before-prepare/nativescript-nodeify.js
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/mike/Documents/temp/nodeify-test/node_modules/nativescript-nodeify/node_modules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.<anonymous> (/Users/mike/Documents/temp/nodeify-test/node_modules/nativescript-nodeify/patch-npm-packages.js:14:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by EddyVerbruggen** [comment]
Thanks Mike, that's fixed in 0.5.1.
